# Generated by Django 5.1.3 on 2024-12-06 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdue',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
