# Generated by Django 5.1.3 on 2024-12-06 13:54

import django.core.validators
import django.db.models.deletion
import validator.views
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=150, verbose_name='contact person')),
                ('phone1', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+233000000000'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Prim. Phone')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+233000000000'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Sec. Phone')),
                ('logo_url', models.FileField(blank=True, max_length=256, null=True, upload_to='organizations', validators=[validator.views.validate_file_size], verbose_name='Logo')),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('active', 'Active'), ('non_active', 'Non Active')], default='active', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
