# Generated by Django 5.1.3 on 2024-12-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='author',
            new_name='artist',
        ),
    ]
