# Generated by Django 5.1.3 on 2024-12-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchServiceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men', models.IntegerField(blank=True, null=True, verbose_name='total mem')),
                ('women', models.IntegerField(blank=True, null=True, verbose_name='total women')),
                ('children1', models.IntegerField(blank=True, null=True, verbose_name='total male children')),
                ('children2', models.IntegerField(blank=True, null=True, verbose_name='total female children')),
                ('vistor', models.IntegerField(blank=True, null=True)),
                ('total_attendees', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ChoirAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=None, max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activity.activity')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
