# Generated by Django 5.1.3 on 2024-12-06 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0002_initial'),
        ('attendance', '0001_initial'),
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choirattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choir_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choirattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choir_member', to='member.member'),
        ),
        migrations.AddField(
            model_name='churchserviceattendance',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_activity', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='churchserviceattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
