# Generated by Django 5.1.3 on 2024-12-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_choirattendance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choirattendance',
            old_name='activities',
            new_name='activity',
        ),
    ]
